articles:
    path: /article
    controller: App\Controller\ArticleController::index

categories:
    path: /category
    controller: App\Controller\CategoryController::index

blog:
    path: /blog
    controller: App\Controller\BlogController::index